/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paneles;

import ConexionBD.ConexionBD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ricardo
 */
public class VentasHechas extends javax.swing.JPanel {

    ConexionBD cn=new ConexionBD();
    public DefaultTableModel tbl = new DefaultTableModel(titulos(), 0){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; //To change body of generated methods, choose Tools | Templates.
        }
    };
    public VentasHechas() {
        initComponents();
        jTable1.setModel(tbl);
        getVentas("select c.*,d.*,u.*,p.*,cli.* from comprobante c inner join detalle_comprobante d on c.ID_COMPROBANTE=d.ID_COMPROBANTE \n" +
"inner join usuario u on c.id_usuario=u.id_usuario inner join Cliente cli on c.id_cliente=cli.id_cliente \n" +
"inner join producto p on d.id_producto=p.id_producto order by d.ID_COMPROBANTE");
    }
    private String [] titulos() {
        String [] titulo={"ID.Comprobante","Cliente","Usuario","producto",
            "Cantidad","Precio","Pago Total","Fecha"};
        return titulo;
    }
    public void getVentas(String sql){
        int f=0;
        try {
            ResultSet rs=cn.Consulta(sql);
            tbl.setRowCount(0);
            
            while(rs.next()){
                f=tbl.getRowCount();
                tbl.setRowCount(f+1);
                tbl.setValueAt(rs.getInt("id_comprobante"), f, 0);
                tbl.setValueAt(rs.getString("apellidos")+" "+rs.getString("nombres"), f, 1);
                tbl.setValueAt(rs.getString("usuario"), f, 2);
                tbl.setValueAt(rs.getString("nombre_producto"), f, 3);
                tbl.setValueAt(rs.getInt("cantidad"), f, 4);
                tbl.setValueAt(rs.getDouble("precio"), f, 5);
                tbl.setValueAt(rs.getDouble("pagototal"), f, 6);
                tbl.setValueAt(rs.getDate("fecha"), f, 7);
            }
            rs.close();
        } catch (SQLException ex) {
            System.out.println("Erro al obtener ventas "+ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFecha = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        try {
            txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Fecha");

        jTextField1.setBackground(new java.awt.Color(255, 102, 102));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Visualizar Ventas hechas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getVentas("select c.*,d.*,u.*,p.*,cli.* from comprobante c inner join detalle_comprobante d on c.ID_COMPROBANTE=d.ID_COMPROBANTE \n" +
"inner join usuario u on c.id_usuario=u.id_usuario inner join Cliente cli on c.id_cliente=cli.id_cliente \n" +
"inner join producto p on d.id_producto=p.id_producto where convert(date,d.fecha)='"+txtFecha.getText()+"' and convert(date,c.fecha_p)='"+txtFecha.getText()+"' order by d.ID_COMPROBANTE\n" +
"");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JFormattedTextField txtFecha;
    // End of variables declaration//GEN-END:variables

    
}
